# Moje první analýza

Tento notebook procvičuje práci s Jupyter Notebooky, numpy a matplotlib.

In [ ]:
# automatický výstup poslední hodnoty v buňce
jmeno = "Jupyter"
verze = 4.2
verze

In [ ]:
# zkus nápovědu – spusť a prohlédni si výstup
len?

In [ ]:
# vypiš balíčky nainstalované v projektu
!uv pip list

In [2]:
import numpy as np
data = np.load("pacienti.npy")
print("Tvar pola:", data.shape)
print("Prvych 5 riadkov:")
print(data[:5])
nazvy = ["Systolicky tlak", "Diastolicky tlak", "Tepova frekvencia"]
for i, nazov in enumerate(nazvy):
    print(f"{nazov}: priemer = {data[:, i].mean():.1f}, std = {data[:,i].std():.1f}")
hypertenzia = data[data[:,0]>=140]
print(f"\nPocet pacientov s hypertenziou: {len(hypertenzia)}")
print(f"\nPriemerny systolicky tlak: {hypertenzia[:,0].mean():.1f} mmHg")
pulzny_tlak = (data[:,0] - data[:, 1]).reshape(-1,1)
data_rozsirena = np.column_stack((data, pulzny_tlak))
print("\nData s pulznym tlakom (prvych 5 riadkov):")
print(data_rozsirena[:5])
index = np.argmax(data[:,2])
print(f"\nPacient s najvzssou tepovou frekvenciou: index {index}")
print(f"Cely zaznam: {data[index]}")


Tvar pola: (20, 3)
Prvych 5 riadkov:
[[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]]
Systolicky tlak: priemer = 124.5, std = 12.7
Diastolicky tlak: priemer = 81.1, std = 7.7
Tepova frekvencia: priemer = 77.0, std = 11.3

Pocet pacientov s hypertenziou: 1

Priemerny systolicky tlak: 141.9 mmHg

Data s pulznym tlakom (prvych 5 riadkov):
[[129.6  78.2  93.   51.4]
 [109.4  73.2  72.   36.2]
 [136.3  92.2  61.   44.1]
 [139.1  78.5  89.   60.6]
 [ 95.7  75.7  80.   20. ]]

Pacient s najvzssou tepovou frekvenciou: index 0
Cely zaznam: [129.6  78.2  93. ]


In [1]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 653.6 kB/s eta 0:00:20
   - -------------------------------------- 0.3/12.6 MB 2.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.6 MB 4.0 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/12.6 MB 5.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/12.6 MB 6.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.6 MB 7.2 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.6 MB 8.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 9.1 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.6 MB 10.1 MB/s eta 0:00:01
   -------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip
